subjects:
  Notification: "Your attention needed"
  Stop: "Task completed"
  SubagentStop: "Subtask completed"

content:
  Notification: |
    Current time is {{timestamp}} 
    
    {{#if message}}
    > {{message}} 
    
    {{/if}}Working directory: {{cwd}} 
    Session ID: {{sessionId}} 
    
    Please open Claude Code terminal for details.
    
    ---
    <small>This email is sent by Claude Code Mailer - The intelligent email notification system that keeps you connected to your AI assistant. 🚀<br>
    Project: https://github.com/LuRenJiasWorld/Claude-Code-Mailer</small> 
  
  Stop: |
    Current time is {{timestamp}} 
    
    {{#if message}}
    > {{message}} 
    
    {{/if}}Working directory: {{cwd}} 
    Session ID: {{sessionId}} 
    
    Please check terminal for details.
    
    ---
    <small>This email is sent by Claude Code Mailer - The intelligent email notification system that keeps you connected to your AI assistant. 🚀<br>
    Project: https://github.com/LuRenJiasWorld/Claude-Code-Mailer</small> 
  
  SubagentStop: |
    Current time is {{timestamp}} 
    
    {{#if message}}
    > {{message}} 
    
    {{/if}}Working directory: {{cwd}} 
    Session ID: {{sessionId}} 
    
    Please check terminal for details.
    
    ---
    <small>This email is sent by Claude Code Mailer - The intelligent email notification system that keeps you connected to your AI assistant. 🚀<br>
    Project: https://github.com/LuRenJiasWorld/Claude-Code-Mailer</small> 

defaults:
  subject: "Notification"
  message: ""